### PR TITLE
CI: Add editorconfig and circle CI config.

### PR DESCRIPTION
**Pull request by danielballan**

### CODE REVIEW

**Comment by danielballan** [comment]
@Mr0grog How did you set up Circle-CI to run on web-monitoring-db PRs? I enable the "Integration" in repo settings, but it looks like you somehow set up a "Webhook" in GH settings for web-monitoring-db, and I can't figure out how that's supposed to go.

 I've mostly only used Travis-CI, but I think we should use Circle-CI consistently.

**Comment by Mr0grog** [comment]
I think you’re meant to set it up from the CircleCI side—it automatically adds everything. Just go to projects in the sidebar, select the EDGI org, and find the repo:

screen shot 2017-05-14 at 1 45 17 pm

**Comment by danielballan** [comment]
Thanks for the screenshot. I did those steps already, as far as I can tell. Maybe I need to merge the circle.yml file into master before the configuration can complete....

**Comment by Mr0grog** [comment]
Oh, I totally missed that this PR is from your fork! I think the problem is almost certainly that support for building forks is off by default (because CI services like this and Travis have seen people use them to run Bitcoin mining code by making PRs to random OSS projects).

You can either set up Circle for your fork or you can turn on support for building all forks in Project Settings → Advanced Settings on Circle:

screen shot 2017-05-14 at 10 48 10 pm

**Pull request merged**
