### PR TITLE
WIP: Html diff render

### PR DESCRIPTION
**Pull request by janakrajchadha**
~~__WIP__~~

I've tried and tested this differ. It works well on the few test cases I've tried it on. 
There are better ways to implement some parts of the differ but most of the ones I've found include the reconstruction of the HTML tree which leads to loss of attribute data from tags like `<head>` and `<body>`. 
Some changes in the source code of `lxml` would also make this job easier but there's probably a good reason they haven't done that.

Please review @danielballan :)

### CODE REVIEW

**Comment by janakrajchadha** [comment]
Fixes #69

**Comment by Mr0grog** [comment]
@janakrajchadha What’s the status on this? Just curious since it sounded like [we came to an agreement](https://github.com/edgi-govdata-archiving/web-monitoring-processing/issues/69#issuecomment-321712752) over a week ago that we should not just remove `ins` and `del` elements and add our own, but there are no updates to this PR since before then. The tests here still look for the addition of simple `ins` and `del` elements, too.

**Comment by janakrajchadha** [comment]
@Mr0grog I went deeper into lxml's code to understand where we could alter it to add our own tags. Turns out that there's no parameter which allows us to pass our own tags, we'll have to alter the source code in a few places. 
Also found out that lxml uses [`difflib`](https://docs.python.org/3/library/difflib.html) in one of the layers for this diff. I had shared the possible paths to take with @danielballan, waiting for his views on it.
Understanding and reconstructing this based on our needs may take a little longer than earlier expected.

**Comment by Mr0grog** [comment]
@danielballan @janakrajchadha does it make sense to merge and deploy this in the mean time, improving the implementation not to cause problems on pages with `<ins>`/`<del>` tags and the like later?

**Comment by Mr0grog** [comment]
Update: decided in weekly meeting to merge this and iterate later, pending a deeper review of the existing implementation here by @danielballan.

**Comment by janakrajchadha** [comment]
@Mr0grog @danielballan I was planning to create my own version of `htmldiff` based on `lxml`'s source code. As discussed earlier, `lxml` uses `InsensitiveSequenceMatcher` which is inherited from `SequenceMatcher` class of `difflib`. The problem we faced with `lxml`'s implementation is that it does not allow custom tags to be added instead of simple `<ins>/<del>` tags.
Anastasia, who has joined us on Slack, has worked on similar tools and I was lucky enough to come across a solution for our problem while going through her diff repositories.
You can take a look at her implementation of [`htmldiff`](https://github.com/anastasia/htmldiffer/blob/develop/htmldiffer/diff.py).
Also, [`lxml's htmldiff_tokens` ](http://lxml.de/api/lxml.html.diff-pysrc.html#htmldiff_tokens).
I'll start working on this.
Let me know if you have any suggestions.

**Comment by danielballan** [comment]
Sounds good. Shall we leave this PR in limbo in the meantime?

**Comment by Mr0grog** [comment]
Sorry I have been slow to respond. Unless someone has a PR they are ready to submit, I would not like to leave this in limbo. I would like to have *something* for our most critical diff, even if we completely replace it in the near future.

**Comment by danielballan** [comment]
That is a very fair point. Post v0 a lot of our diffing stuff might get superceded by collaborative projects, but this will suffice for v0. I'll add some additional tests. @janakrajchadha, carry on with your collaborative work with Anastasia.

**Comment by janakrajchadha** [comment]
@danielballan I'm not sure why I'm getting the `FileNotFound` error. I'm looking for reasons.
Would you rather have all the test cases defined in the code itself?

**Comment by danielballan** [comment]
Good test cases. As you've discovered, bundling static files into a Python package properly is not straightforward. We'll probably find a good reason to do that later (and I'll show you how) but in this case I think it's easier and better to just define the test cases in the code itself.

**Comment by janakrajchadha** [comment]
@danielballan Fixed, should this be merged now?

**Comment by danielballan** [comment]
Great, thanks @janakrajchadha.

**Pull request merged**
