### PR TITLE
Sketch out sphinx documentation.

### PR DESCRIPTION
**Pull request by danielballan**
There is obviously much more we could add here, but I would prefer
to merge this sooner than later under the theory that some documentation
is better than none.

Ultimately, I would like Circle-CI builds of master to automatically publish
this documentation to gh-pages. I typically use a tool called doctr
(documentation + Travis-CI) to do this, but it
[does not yet support Circle-CI](https://github.com/drdoctr/doctr/issues/189).
I may add support for Circle-CI to doctr myself. In the meantime, I intend
to publish updates manually.

### CODE REVIEW

**Comment by danielballan** [comment]
Unless someone objects by tonight, I'll merge this to get the framework in place and invite others to iterative on it in parallel.

**Comment by Mr0grog** [comment]
Sorry I didn’t get to this earlier. It’s awesome to have, though! Some post-facto questions:

- Should we combine `test-requirements.txt` and `docs-requirements.txt` into a `dev-requirements.txt`?
- The generated docs for web_monitoring.db don’t include the constructor or `from_env` class method. Is that because they aren’t listed here? https://github.com/edgi-govdata-archiving/web-monitoring-processing/pull/116/files#diff-0c49c12769a66ba488a8759ff1f48532R21 (I somehow haven’t actually used Sphinx before)
- We should add instructions for building docs to the README

Happy to file issues for any/all of these if you want, @danielballan.

**Comment by Mr0grog** [comment]
> I would like Circle-CI builds of master to automatically publish
this documentation to gh-pages.

Also, that sounds *wonderful.*

**Comment by asmeurer** [comment]
> I may add support for Circle-CI to doctr myself.

:+1:

**Comment by danielballan** [comment]
Hey @asmeurer! I have a WIP branch. Are you aware of any parallel efforts to do this?

**Comment by asmeurer** [comment]
I'm not aware of any parallel efforts.

I'm the only person working on doctr right now (Gil is busy with his new job), and I haven't done any work on Circle stuff.

**Pull request merged**
