### PR TITLE
add missing cython dependency

### PR DESCRIPTION
**Pull request by jsnshrmn**
when building in a clean enterprise linux environment, I found that I didn't have cython, but that I needed it.

### CODE REVIEW

**Comment by danielballan** [comment]
Is that a build-time dep? I think adding it to the `environment.yml` or `requirements.txt` will not help in this case. Distutils and setuptools do not presently have a way to specific build-time deps, AFAIK.

**Comment by jsnshrmn** [comment]
This is happening for me in ansible testing. In this case, the following task was failing:
```
- name: Install web-monitoring-processing dependencies using conda.
  # TODO Need a proper conda ansible role to check whether the existing env is
  # up to date. This *always* re-builds the env.
  shell: "/opt/conda/bin/conda-env create --quiet --force -f /srv/checkout/web
-monitoring-processing/environment.yml -p /opt/conda/envs/web-monitoring-proce
ssing"
  become: true
  tags: ['conda']
```
having cython available on my system didn't make an impact, but adding it to the environment file allowed the task to complete happily. Not a big conda user myself, so I'm not really clear on the implications, other than 0 is a happy status code.

**Comment by jsnshrmn** [comment]
and, I realized I didn't answer your question: this is a build time dep, but I don't know if it is also a run time dep.

**Comment by danielballan** [comment]
I understand what's happening. Cython is a build-time dep, and would not be necessary if all of the packages in the `environment.yml` were conda packages. But we employ a `block of pip packages`, an escape hatch provided by conda for when packages aren't available via conda. That block includes one or more packages that require Cython to build. Fortunately, because the proper conda packages are installed first, adding Cython as a runtime dep makes it available by the time the pip packages build.

I'll open and self-assign an issue to fix this properly by packaging more things for conda.

I notice the tests are failing because they rely on certain env vars, some of them secret, that aren't set on your fork, @jsnshrmn. As a short-term fix, let's get him set: I'll share info via Keybase. But this reminds me that we had planned to refactor the tests to make them pass on any contributor's fork. I recall the discussion but couldn't find an issue, so I opened #222.

**Comment by Mr0grog** [comment]
> I notice the tests are failing because they rely on certain env vars, some of them secret, that aren't set on your fork, @jsnshrmn. As a short-term fix, let's get him set: I'll share info via Keybase. But this reminds me that we had planned to refactor the tests to make them pass on any contributor's fork. I recall the discussion but couldn't find an issue, so I opened #222.

Yeah, that’s not the problem; all that work was done many months ago in #186. This branch forks from `master` as of *February;* there have been a lot of changes (like #186) since then. You’ll also notice it is using CircleCI 1.0. This branch just needs rebasing on Master.

**Comment by Mr0grog** [comment]
Is old. (This branch is the green line; master is the red on the left.)

git-history

**Comment by jsnshrmn** [comment]
Yeah, I saw that this was pretty far behind master, I just figured I'd start with the git revisions that the ansible test inventory was pointed at since that was a known state.

**Comment by danielballan** [comment]
Woah. I rebased on `master` and pushed (`--force-with-lease`) and the GH UI lost its mind. Locally the diff against `master` looks fine:

```diff
diff --git a/environment.yml b/environment.yml
index 8838991..7981138 100644
--- a/environment.yml
+++ b/environment.yml
@@ -1,6 +1,7 @@
 name: "web-monitoring-processing"
 dependencies:
 - beautifulsoup4
+- cython
 - python-dateutil
 - docopt
 - lxml
```

Going to close/reopen.

**Comment by danielballan** [comment]
Oh, I see what happened here. @jsnshrmn I pushed your commit to `upstream/conda-env-file`. Closing.

**Pull request closed without merging**
