### PR TITLE
added list of link tests

### PR DESCRIPTION
**Pull request by weatherpattern**
Created simple test cases for list of links described in #124 

Added cases for changes in text and urls, and adding and remove list items.

### CODE REVIEW

**Comment by danielballan** [comment]
Ditto -- sorry for taking too long to look at this. Yep, gotta add these files to the list of cases, and then this should be good to merge.

**Comment by weatherpattern** [comment]
Sorry to have jumped the gun on this. When I run run_test.py, test_html_diff.py passes but I get 4 failures and a few others from other tests. I am having trouble understanding the error output. Could we book some time to go over it?
Test output is attached.

[run_test_output.txt](https://github.com/edgi-govdata-archiving/web-monitoring-processing/files/1557067/run_test_output.txt)

**Comment by danielballan** [comment]
The Circle-CI logs show that the tests are now being run and that they pass, so this is good to merge. It looks like you have a local dev issue. Are you setting environment variables with a valid web-monitoring-db username and password? See `.env.example` for a template. I'm happy to provide follow-up support over Slack. It's possible our documentation on this is not complete or clear.

**Comment by Mr0grog** [comment]
Heh, we actually solved this at the start of the meeting, @danielballan. It was a problem with CircleCI settings and the fact that @weatherpattern is developing on his own fork (so env vars were not shared).

I set it to share vars temporarily (back off now), but that’s not really safe. I wish we could create a list of privileged forks in Circle, but it doesn’t seem like you can. I guess the solutions are:

1. Work on a branch in this repo instead of a fork
2. Set up CircleCI specifically for your fork with the right env vars (@weatherpattern was worried this might be complicated, but I don’t think it should be too bad—the hard part is just knowing the right vars and values to set)

**Comment by weatherpattern** [comment]
For now I'm happy to work with on a work on a branch in this repo.
I'll put setting up circleci on my to do list.

**Pull request merged**
